---
- include_vars: "{{ ansible_os_family|lower }}.yml"

- name: ensure powerline package is installed
  package:
    name: powerline

- name: ensure vim-powerline package is installed
  package:
    name: vim-powerline
  when: powerline_vim

- name: ensure tmux-powerline package is installed
  package:
    name: tmux-powerline
  when: powerline_tmux

- name: ensure powerline script is installed
  template:
    src: powerline.sh.j2
    dest: /etc/bash_powerline.sh

- name: retrieve the list of home directories
  command: ls /home
  register: home_dirs
  changed_when: false
  check_mode: no

- name: ensure default top theme for powerline is configured
  lineinfile:
    dest: "{{ powerline_config_file }}"
    line: "\t\t\"default_top_theme\": \"{{ powerline_default_top_theme }}\","
    regexp: "default_top_theme"
    insertbefore: "term_truecolor"

- name: ensure powerline for shell is configured
  template:
    src: powerline-shell.json.j2
    dest: "{{ powerline_themes_directory }}/shell/default.json"

- name: ensure powerline for tmux is configured
  template:
    src: powerline-tmux.json.j2
    dest: "{{ powerline_themes_directory }}/tmux/default.json"
